#+TITLE: Dotfiles Readme
#+AUTHOR: Adam McCullough

#+CAPTION: Build Status on Circle-CI
#+ATTR_HTML: :alt dotfiles.svg
[[https://circleci.com/gh/TheWizardTower/dotfiles][https://circleci.com/gh/TheWizardTower/dotfiles.svg?style=shield&circle-token:=circle-token]]
* Install
Do a git clone the repo, and run install.sh. Remove the ~/.gitconfig file if you aren't me. :)

* Dependencies
[[https://github.com/anishathalye/dotbot][Dotbot]] needs python and the python YAML library.
oh-my-fish needs Fish and Git. The Peco plugin for omf needs peco, which is in go.
Emacs uses quite a few external tools, particularly for error-checking and linting. This involves reaching out to binaries written in Go, Haskell, as well as tools for Perl, Python, Clojure, regexes, rpm files and YAML. I use [[https://github.com/rdallasgray/pallet][Pallet]] and [[https://github.com/cask/cask][Cask]] to manage the emacs packages.

* In Progress
** Fix Cabal
Cabal-install is a rather awful package manager.

On any Distro, I expect this operation to work:

$my_package_manager install $package; $my_package_manager install $package

With cabal-install, this does not. It says that you're risking a re-install, and that might break things.

Furthermore, if I can install a given set of packages one at a time, I fully expect to be able to install them in one batch command. With cabal-install, this is not the case.

The only idea I've come across that consistently works is (cringe) building the packages statically, inside a container. I only need a handful of packages (for now), so this wouldn't be tremendously onerous. It could even be done in parallel.

For more reading: https://ivanmiljenovic.wordpress.com/2010/03/15/repeat-after-me-cabal-is-not-a-package-manager/
** Fix Circle-CI testing.
My Circle-CI tests miss a lot. There have been cases where the Cask file had the libraries for what was sourced directly in my init files, but not for the various mode-hooks I've added. Vim is still basically completely busted. For a long time, the dotbot setup wouldn't reliably work, up to and including issues with Cabal, a bad URL for oh-my-fish and Cask, and more.
** Modal bindings for XMonad.
Something like this: https://www.youtube.com/watch?v=_qZliI1BKzI

I've made some progress on this by making some multi-step key bindings. But nothing like command mode in vim. I suspect this will take a library for xmonad.
* Wishlist
** Literate programming for emacs
Dotfiles settings aren't the most... readable things in the world. And being forced to explain settings clearly only ends in good things.
** Travis-CI testing.
Maybe someday. Containers-as-tests are rather lovely.
