#+TITLE: Dotfiles Readme
#+AUTHOR: Adam McCullough

#+CAPTION: Build Status on Circle-CI
#+ATTR_HTML: :alt dotfiles.svg 
[[https://circleci.com/gh/TheWizardTower/dotfiles.svg?style=svg]]

* Install
Ideally, git clone the repo, and run install.sh. 

* Dependencies
The installer requires Emacs 24 and Python for Cask, Golang, Cabal, Fish for oh-my-fish, and git for cloning a few side plugins. The Docker build environments  

* In Progress
** Clean up any references to /home/amccullough.
Make it just reference ~/.
** Convert to using site-start.d for configuring modules and settings whenever possible.
This is mostly done. There are still a few stray things in emacs (some of which can't be moved out successfully), and the numbering of the init files is a little arbitrary and needs to be cleaned up.

** Clean up the install process.
It's kind of broken, especially with all the stuff I'm doing with it. Ideally convert to https://github.com/anishathalye/dotbot. Most importantly, make it idempotent, so that puppet can just call it.


* Wishlist
** Literate programming for emacs
Dotfiles settings aren't the most... readable things in the world. And being forced to explain settings clearly only ends in good things.
** Modal bindings for XMonad.
Something like this: https://www.youtube.com/watch?v=_qZliI1BKzI
** Better tests in circle-ci.
**** Check my vim config. 
**** Make sure puppet did everything correctly. 
**** Fix intermittent failures because Fedora migrated to dnf and some packages still reference yum.
** Travis-CI testing.
