# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/amccullough/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#
flags: {}
extra-package-dbs: []
packages: []
extra-deps:
    - atto-lisp-0.2.2.1
    - base-orphans-0.5.4
    - bifunctors-5.3
    - cabal-helper-0.6.3.0
    - conceit-0.4.0.0
    - ghc-7.10.2
    - ghc-exactprint-0.5.0.1
    - ghc-mod-5.5.0.0
    - ghc-syb-0.1.2.2
    - network-bytestring-0.1.3.4
    - rosezipper-0.2
    - pipes-transduce-0.4
    - process-streaming-0.9.1.1
    - ShellCheck-0.4.1
    - Strafunski-StrategyLib-5.0.0.8
    - syz-0.2.0.0
    - transformers-compat-0.5.1.4
    - xmonad-0.11.1
    - xmonad-contrib-0.11.4
    - X11-xft-0.3.1

resolver: lts-3.15
