(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/")
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(setq package-selected-packages
      (quote
       (
ace-flyspell
ace-isearch
ace-jump-buffer
ace-jump-helm-line
ace-popup-menu
ace-window
ack-menu
ag
airline-themes
ansible
ansible-doc
auto-yasnippet
bash-completion
benchmark-init
better-registers
bm
bookmark+
browse-at-remote
browse-kill-ring+
cargo
caskxy
cfengine-code-style
clojure-mode
clojure-snippets
cmd-to-echo
cmds-menu
commander
comment-dwim-2
common-lisp-snippets
company-ansible
company-c-headers
company-cabal
company-flx
company-ghc
company-ghci
company-go
company-irony
company-irony-c-headers
company-math
company-php
company-quickhelp
company-shell
company-statistics
company-try-hard
company-web
conkeror-minor-mode
counsel
crontab-mode
cus-edit+
cycle-quotes
decide
diff-hl
diffview
diminish
dired+
dired-quick-sort
dired-rainbow
discover
discover-my-major
docker
dockerfile-mode
dropbox
dsvn
ebal
ecb
el-sprunge
emamux
erefactor
evil-anzu
evil-args
evil-avy
evil-cleverparens
evil-commentary
evil-easymotion
evil-exchange
evil-extra-operator
evil-god-state
evil-matchit
evil-mc
evil-nerd-commenter
evil-numbers
evil-org
evil-replace-with-register
evil-search-highlight-persist
evil-smartparens
evil-space
evil-surround
evil-tabs
evil-terminal-cursor-changer
evil-tutor
evil-vimish-fold
evil-visual-mark-mode
exec-path-from-shell
expand-region
facemenu+
faces+
firecode-theme
fish-mode
flycheck-bashate
flycheck-cask
flycheck-clojure
flycheck-color-mode-line
flycheck-ghcmod
flycheck-gometalinter
flycheck-haskell
flycheck-hdevtools
flycheck-ledger
flycheck-pos-tip
flycheck-rust
flycheck-stack
flylisp
flymd
flyspell-correct-helm
fold-this
fzf
ggtags
ghc-imported-from
ghci-completion
git-messenger
gnomenm
go-complete
go-direx
go-dlv
go-errcheck
go-gopath
go-projectile
go-scratch
go-snippets
golden-ratio
golint
gore-mode
gotest
gotham-theme
govet
guru-mode
haskell-snippets
hasky-extensions
hayoo
helm-ack
helm-ag
helm-ag-r
helm-anything
helm-bind-key
helm-c-yasnippet
helm-cider
helm-cider-history
helm-commandlinefu
helm-company
helm-descbinds
helm-ext
helm-flycheck
helm-flyspell
helm-fuzzier
helm-fuzzy-find
helm-ghc
helm-git
helm-gitignore
helm-go-package
helm-gtags
helm-hayoo
helm-helm-commands
helm-hoogle
helm-ispell
helm-make
helm-open-github
helm-package
helm-projectile
helm-pt
helm-tramp
help+
highlight-symbol
hindent
hl-line+
hl-spotlight
idle-highlight-mode
ido-vertical-mode
indent-guide
init-loader
insert-shebang
intero
iregister
judge-indent
ledger-mode
linum-relative
lively
magic-filetype
magit
magit-filenotify
magit-find-file
magit-gh-pulls
magit-gitflow
magit-svn
markdown-mode+
menu-bar+
miniedit
names
org-dashboard
org-dotemacs
org-download
org-projectile
org-table-comment
orgit
pallet
paradox
pdf-tools
persistent-soft
php+-mode
plsense
popwin
powerline-evil
prodigy
project-shells
projectile-ripgrep
puppet-mode
quelpa
quickref
racer
rainbow-delimiters
rats
register-list
relative-line-numbers
rg
ripgrep
roguel-ike
rpm-spec-mode
rpn-calc
runner
rust-mode
sane-term
scratch-ext
sicp
smartscan
spu
srefactor
stickyfunc-enhance
sublimity
swiper
swiper-helm
symon
tabbar-ruler
telephone-line
tramp-term
vdiff
vim-empty-lines-mode
visual-regexp-steroids
vline
warm-night-theme
which-key
window-layout
winring
yaml-mode
)))

;; install required
 (dolist (package package-selected-packages)
   (unless (package-installed-p package)
     (package-install package)))


; ;; upgrade installed
(save-window-excursion
   (package-list-packages t)
   (package-menu-mark-upgrades)
   (package-menu-execute t))
